# Analyzing Patient Data

Making sense of the data.

## `import numpy`

To load the .CSV data we will use a library called Numpy.

In order to load our inflammation data,
we need to [import](reference.html#import) a library called NumPy.
In general you should use this library if you want to do fancy things with numbers,
especially if you have matrices or arrays.
We can load NumPy using:

In [1]:
import numpy

Importing a library is like getting a piece of lab equipment out of a storage locker
and setting it up on the bench. Libraries provide additional functionality to the basic Python package, much like a new piece of equipment adds functionality to a lab space.

### Once you've loaded the library ...

We can ask the library to read our data file for us:

In [2]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])


The expression `numpy.loadtxt(...)` is a [function call](reference.html#function-call)
that asks Python to run the function `loadtxt` that belongs to the `numpy` library.
This [dotted notation](reference.html#dotted-notation) is used everywhere in Python
to refer to the parts of things as `thing.component`.

`numpy.loadtxt` has two [parameters](reference.html#parameter):
the name of the file we want to read,
and the [delimiter](reference.html#delimiter) that separates values on a line.
These both need to be character strings (or [strings](reference.html#string) for short),
so we put them in quotes.

When we are finished typing and press Shift+Enter,
the notebook runs our command.
Since we haven't told it to do anything else with the function's output,
the notebook displays it.
In this case,
that output is the data we just loaded.
By default,
only a few rows and columns are shown
(with `...` to omit elements when displaying big arrays).
To save space,
Python displays numbers as `1.` instead of `1.0`
when there's nothing interesting after the decimal point.

Our call to `numpy.loadtxt` read our file,
but didn't save the data in memory.
To do that,
we need to [assign](reference.html#assignment) the array to a [variable](reference.html#variable).
A variable is just a name for a value,
such as `x`, `current_temperature`, or `subject_id`.
Python's variables must begin with a letter and are [case sensitive](reference.html#case-sensitive).
We can create a new variable by assigning a value to it using `=`.
As an illustration,
let's step back and instead of considering a table of data,
consider the simplest "collection" of data,
a single value.
The line below assigns the value `55` to a variable `weight_kg`:

### Variables

#### The symbol "`=`"

We can create a new variable by assigning a value to it using "`=`".

Python's variables must begin with a letter and are case sensitive.


In [8]:
weight_kg = 54
print(weight_kg)

54


#### Once a variable has a value we can:

In [9]:
# print it
print(weight_kg)

54


In [10]:
# do arithmetic with it:
print('weight in pounds:', 2.2 * weight_kg) 

weight in pounds: 118.80000000000001


In [12]:
# change its value
weight_kg = 58
print('weight in kilograms is now:', weight_kg)

weight in kilograms is now: 58


Assigning a value to one variable does *not* change the values of other variables.

![Variables as Sticky Notes](fig/python-sticky-note-variables-01.svg)

In [15]:
weight_lb = 2.2 * weight_kg
print('weight in kilograms:', weight_kg, 
      'and in pounds:', weight_lb)

weight in kilograms: 100.0 and in pounds: 220.00000000000003


In [17]:
weight_kg = 100
print('weight in kilograms is now:', weight_kg, 
      'and weight in pounds is still:', weight_lb)

weight in kilograms is now: 100 and weight in pounds is still: 220.00000000000003


### `whos`

In IPython the `whos` command shows the variables in memory.

In [18]:
whos

Variable    Type      Data/Info
-------------------------------
numpy       module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
weight_kg   int       100
weight_lb   float     220.00000000000003


### Check your understanding {.challenge}

Draw diagrams showing what variables refer to what values after each statement in the following program:

In [19]:
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20

Draw a table showing the values of the variables in this program after each statement is executed. In simple terms, what do the last three lines of this program do?

In [22]:
lowest = 1.0
highest = 3.0
low 

1.0


What is the final value of position in the program below? (Try to predict the value without running the program, then check your prediction.)

In [23]:
initial = "left"
position = initial
initial = "right"

print(position)

left


## Sorting out references {.challenge}

What does the following program print out?

In [24]:
first, second = 'Grace', 'Hopper'

third, fourth = second, first

print(third, fourth)

Hopper Grace


### Assign arrays

Just as we can assign a single value to a variable, we can also assign an array of values:

In [25]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', 
                     delimiter=',')

This statement doesn't produce any output because assignment doesn't display anything.
If we want to check that our data has been loaded,
we can print the variable's value:

In [26]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [29]:
# what type is the data
print(type(data))

<class 'numpy.ndarray'>


The output tells us that `data` currently refers to an N-dimensional array created by the NumPy library. These data correspond to arthritis patients' inflammation. 

The rows are the individual patients and the columns are their daily inflammation measurements.

We can see what its [shape](reference.html#shape) is like this:

In [30]:
print(data.shape)

(60, 40)


This tells us that `data` has 60 rows and 40 columns. When we created the
variable `data` to store our arthritis data, we didn't just create the array, we also
created information about the array, called [members](reference.html#member) or
attributes. This extra information describes `data` in
the same way an adjective describes a noun.
`data.shape` is an attribute  of `data` which described the dimensions of `data`.
We use the same dotted notation for the attributes of variables
that we use for the functions in libraries
because they have the same part-and-whole relationship.

If we want to get a single number from the array,
we must provide an [index](reference.html#index) in square brackets,
just as we do in math:

### Indexing

In [32]:
print('first value in data:', data[0, 1])

first value in data: 0.0


In [33]:
print('middle value in data:', data[30, 20])

middle value in data: 13.0


The expression `data[30, 20]` may not surprise you,
but `data[0, 0]` might.
Programming languages like Fortran and MATLAB start counting at 1,
because that's what human beings have done for thousands of years.

Languages in the C family (including C++, Java, Perl, and Python) count from 0
because that's simpler for computers to do.

As a result,
if we have an M&times;N array in Python,
its indices go from 0 to M-1 on the first axis
and 0 to N-1 on the second.

It takes a bit of getting used to,
but one way to remember the rule is that
the index is how many steps we have to take from the start to get the item we want.

### Slicing

An index like `[30, 20]` selects a single element of an array,
but we can select whole sections as well.

For example,
we can select the first ten days (columns) of values
for the first four patients (rows) like this:


In [36]:
print(data[0:4, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


#### What does `0:4` mean?

- Start at `0` and go up to, but not including, `4`.
- **The rule**: difference between the upper and lower bounds is the number of values in the slice.

The [slice](reference.html#slice) `0:4` means,
"Start at index 0 and go up to, but not including, index 4."

Again,
the up-to-but-not-including takes a bit of getting used to,
but the rule is that the difference between the upper and lower bounds is the number of values in the slice.

We don't have to start slices at 0:

In [65]:
print(data[2:10, 0:10].shape)

(8, 10)


We also don't have to include the upper and lower bound on the slice.

If we don't include the lower bound, Python uses 0 by default;

if we don't include the upper, the slice runs to the end of the axis, and if we don't include either (i.e., if we just use ':' on its own), the slice includes everything:

In [48]:
small = data[:3, 36:]
print(small) 

print(small[:3, 38:49])

[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
[]


## Slicing strings {.challenge}

A section of an array is called a [slice](reference.html#slice).
We can take slices of character strings as well:

In [60]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
print('example', element[:])

first three characters: oxy
last three characters: gen
example 


What is the value of `element[:4]`?
What about `element[4:]`?
Or `element[:]`?

What is `element[-1]`?
What is `element[-2]`?

Given those answers,
explain what `element[1:-1]` does.

## Thin slices {.challenge}

The expression `element[3:3]` produces an [empty string](reference.html#empty-string), i.e., a string that contains no characters.

If `data` holds our array of patient data, what does `data[3:3, 4:4]` produce? What about `data[3:3, :]`?

In [62]:
data[3:3, :]

array([], shape=(0, 40), dtype=float64)

## Looking for help

In [69]:
numpy.loadtxt?

### Arithmetical operations

How to perform common mathematical operations on their values?

Arrays also know how to perform common mathematical operations on their values.

The simplest operations with data are arithmetic:
add, subtract, multiply, and divide.

When you do such operations on arrays, the operation is done on each individual element of the array.

Thus:

#### With scalar values

In [70]:
doubledata = data * 2.0

In [73]:
print(doubledata[:3, 36:])

[[ 4.  6.  0.  0.]
 [ 2.  2.  0.  2.]
 [ 4.  4.  2.  2.]]


#### With other arrays

If, instead of taking an array and doing arithmetic with a single value (as above) you did the arithmetic operation with another array of the same shape, the operation will be done on corresponding elements of the two arrays.

Thus:

In [74]:
tripledata = doubledata + data
tripledata[:3, 36:]

array([[ 6.,  9.,  0.,  0.],
       [ 3.,  3.,  0.,  3.],
       [ 6.,  6.,  3.,  3.]])

### Other operations

Other more complex operations

Often, we want to do more than add, subtract, multiply, and divide values of data.

Arrays also know how to do more complex operations on their values.

If we want to find the average inflammation for all patients on all days, for example, we can just ask the array for its mean value

In [ ]:
print(data.mean())

`mean` is a [method](reference.html#method) of the array,
i.e., a function that belongs to it in the same way that the member `shape` does.

`mean` is a [method](reference.html#method) of the array,
i.e., a function that belongs to it in the same way that the member `shape` does.

If variables are nouns, methods are verbs:
they are what the thing in question knows how to do.

We need empty parentheses for `data.mean()`, even when we're not passing in any parameters, to tell Python to go and do something for us. `data.shape` doesn't need `()` because it is just a description but `data.mean()`  requires the `()` because it is an action.

#### NumPy arrays have lots of useful methods:

In [ ]:
print('maximum inflammation:', data.max())
print('minimum inflammation:', data.min())
print('standard deviation:', data.std())

In [ ]:
patient_0 = data[0, :] # 0 on the first axis, everything on the second
print('max inflammation for patient 0:', patient_0.max())

We don't actually need to store the row in a variable of its own.

Instead, we can combine the selection and the method call:

We don't actually need to store the row in a variable of its own.

In [ ]:
print('max inflammation for patient 0:', data[0, :].max())

When analyzing data, though, we often want to look at partial statistics, such as the maximum value per patient
or the average value per day.

One way to do this is to create a new temporary array of the data we want, then ask it to do the calculation:

### The `axis` argument

What if we need the maximum inflammation for all patients?

What if we need the maximum inflammation for *all* patients (as in the next diagram on the left), or the average for each day (as in the
diagram on the right)? 

As the diagram below shows, we want to perform the
operation across an axis:

![Operations Across Axes](fig/python-operations-across-axes.svg)

To support this, most array methods allow us to specify the axis we want to work on.
If we ask for the average across axis 0 (rows in our 2D example), we get:

If we ask for the average across axis 0, we get:

In [ ]:
print(data.mean(axis=0))

As a quick check, we can ask this array what its shape is:

In [ ]:
print(data.mean(axis=0).shape)

the average inflammation per day for all patients.

The expression `(40,)` tells us we have an N&times;1 vector,
so this is the average inflammation per day for all patients.

If we average across axis 1 (columns in our 2D example), we get:

In [ ]:
print(data.mean(axis=1))

which is the average inflammation per patient across all days.

In [ ]:
data.mean(axis=1).shape

### Plotting with Matplotlib

*"The purpose of computing is insight, not numbers."* Richard Hamming

The mathematician Richard Hamming once said,
"The purpose of computing is insight, not numbers,"
and the best way to develop insight is often to visualize data.

Visualization deserves an entire lecture (or course) of its own, but we can explore a few features of Python's `matplotlib` library here.

While there is no "official" plotting library,
this package is the de facto standard.

First, we will import the `pyplot` module from `matplotlib` and use two of its functions to create and display a heat map of our data:

In [ ]:
import matplotlib.pyplot
image  = matplotlib.pyplot.imshow(data)
matplotlib.pyplot.show()

#### Some Jupyter magic...

## Some IPython magic

If you're using an IPython / Jupyter notebook,
you'll need to execute the following command
in order for your matplotlib images to appear
in the notebook when `show()` is called:

> ~~~ {.python}
> % matplotlib inline
> ~~~

In [ ]:
%matplotlib inline

> The `%` indicates an IPython magic function -
> a function that is only valid within the notebook environment.
> Note that you only have to execute this function once per notebook.

In [ ]:
import matplotlib.pyplot
image  = matplotlib.pyplot.imshow(data)
matplotlib.pyplot.show()

In [ ]:
#Let's take a look at the average inflammation over time:

ave_inflammation = data.mean(axis=0)
ave_plot = matplotlib.pyplot.plot(ave_inflammation)
matplotlib.pyplot.show()

In [ ]:
#Let's have a look at two other statistics:

max_plot = matplotlib.pyplot.plot(data.max(axis=0))
matplotlib.pyplot.show()

In [ ]:
min_plot = matplotlib.pyplot.plot(data.min(axis=0))
matplotlib.pyplot.show()

You can group similar plots in a single figure using subplots.

In [ ]:
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

axes1 = fig.add_subplot(1, 3, 1)
axes2 = fig.add_subplot(1, 3, 2)
axes3 = fig.add_subplot(1, 3, 3)

axes1.set_ylabel('average')
axes1.plot(data.mean(axis=0))

axes2.set_ylabel('max')
axes2.plot(data.max(axis=0))

axes3.set_ylabel('min')
axes3.plot(data.min(axis=0))

fig.tight_layout()

matplotlib.pyplot.show()

![The Previous Plots as Subplots](fig/01-numpy_80_0.png)

Let's take a look at the average inflammation over time:

~~~ {.python}
ave_inflammation = data.mean(axis=0)
ave_plot = matplotlib.pyplot.plot(ave_inflammation)
matplotlib.pyplot.show()
~~~

![Average Inflammation Over Time](fig/01-numpy_73_0.png)

Here,
we have put the average per day across all patients in the variable `ave_inflammation`,
then asked `matplotlib.pyplot` to create and display a line graph of those values.
The result is roughly a linear rise and fall,
which is suspicious:
based on other studies,
we expect a sharper rise and slower fall.
Let's have a look at two other statistics:

~~~ {.python}
max_plot = matplotlib.pyplot.plot(data.max(axis=0))
matplotlib.pyplot.show()
~~~

![Maximum Value Along The First Axis](fig/01-numpy_75_1.png)

~~~ {.python}
min_plot = matplotlib.pyplot.plot(data.min(axis=0))
matplotlib.pyplot.show()
~~~

![Minimum Value Along The First Axis](fig/01-numpy_75_3.png)

The maximum value rises and falls perfectly smoothly,
while the minimum seems to be a step function.
Neither result seems particularly likely,
so either there's a mistake in our calculations
or something is wrong with our data.

You can group similar plots in a single figure using subplots.
This script below uses a number of new commands. The function `matplotlib.pyplot.figure()`
creates a space into which we will place all of our plots. The parameter `figsize`
tells Python how big to make this space. Each subplot is placed into the figure using
its `add_subplot` method. The `add_subplot` method takes 3 parameters. The first denotes
how many total rows of subplots there are, the second parameter refers to the
total number of subplot columns, and the final parameters denotes which subplot
your variable is referencing (left-to-right, top-to-bottom). Each subplot is stored in a
different variable (`axes1`, `axes2`, `axes3`). Once a subplot is created, the axes can
be titled using the `set_xlabel()` command (or `set_ylabel()`).
Here are our three plots side by side:

~~~ {.python}
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

axes1 = fig.add_subplot(1, 3, 1)
axes2 = fig.add_subplot(1, 3, 2)
axes3 = fig.add_subplot(1, 3, 3)

axes1.set_ylabel('average')
axes1.plot(data.mean(axis=0))

axes2.set_ylabel('max')
axes2.plot(data.max(axis=0))

axes3.set_ylabel('min')
axes3.plot(data.min(axis=0))

fig.tight_layout()

matplotlib.pyplot.show()
~~~

![The Previous Plots as Subplots](fig/01-numpy_80_0.png)

The [call](reference.html#function-call) to `loadtxt` reads our data,
and the rest of the program tells the plotting library
how large we want the figure to be,
that we're creating three subplots,
what to draw for each one,
and that we want a tight layout.
(Perversely,
if we leave out that call to `fig.tight_layout()`,
the graphs will actually be squeezed together more closely.)

> ## Check your understanding: plot scaling {.challenge}
>
> Why do all of our plots stop just short of the upper end of our graph?

> ## Check your understanding: drawing straight lines {.challenge}
>
> Why are the vertical lines in our plot of the minimum inflammation per day not perfectly vertical?

> ## Make your own plot {.challenge}
>
> Create a plot showing the standard deviation (`numpy.std`) of the inflammation data for each day across all patients.

> ## Moving plots around {.challenge}
>
> Modify the program to display the three plots on top of one another instead of side by side.

In [ ]:
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

axes1 = fig.add_subplot(1, 3, 1)
axes2 = fig.add_subplot(1, 3, 2)
axes3 = fig.add_subplot(1, 3, 3)

axes1.set_ylabel('average')
axes1.plot(data.mean(axis=0))

axes2.set_ylabel('max')
axes2.plot(data.max(axis=0))

axes3.set_ylabel('min')
axes3.plot(data.min(axis=0))

fig.tight_layout()

matplotlib.pyplot.show()

> ## Check your understanding: plot scaling {.challenge}
>
> Why do all of our plots stop just short of the upper end of our graph?

> ## Check your understanding: drawing straight lines {.challenge}
>
> Why are the vertical lines in our plot of the minimum inflammation per day not perfectly vertical?

> ## Make your own plot {.challenge}
>
> Create a plot showing the standard deviation (`numpy.std`) of the inflammation data for each day across all patients.

> ## Moving plots around {.challenge}
>
> Modify the program to display the three plots on top of one another instead of side by side.